version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data

  whatsapp:
    build: .
    ports:
      - "3001:3001"
    environment:
      - REDIS_URL=redis://redis:6379
      - API_KEY=test-api-key-123
      - FRONTEND_URL=http://localhost:5173
    depends_on:
      - redis
    volumes:
      - ./auth-sessions:/app/auth-sessions

volumes:
  redis-data:
