global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'plubot-monitor'

scrape_configs:
  # WhatsApp microservice metrics
  - job_name: 'whatsapp-service'
    static_configs:
      - targets: ['whatsapp-service:9090']
        labels:
          service: 'whatsapp'
          environment: 'production'
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Redis exporter (optional)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
        labels:
          service: 'redis'
    
  # Node exporter for system metrics (optional)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          service: 'system'

# Alerting rules
rule_files:
  - 'alerts.yml'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']
